version: "3.8"

services:
  app:
    container_name: lambda-app-frontend
    image: lambda-app-frontend
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 5173:80